services:
  frontend:
    image: samurcorrea/movie-reviews-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - movie-reviews-network
    restart: unless-stopped

  backend:
    image: samurcorrea/movie-reviews-backend:latest
    ports:
      - "5000:5000"
    networks:
      - movie-reviews-network
    restart: unless-stopped

networks:
  movie-reviews-network:
    driver: bridge
